print('Enter first point:')
x1 = float(input('x1 = '))
y1 = float(input('y1 = '))
print('Enter second point:')
x2 = float(input('x2= '))
y2 = float(input('y2 = '))
xp = float(input('Enter point to be interpolated: '))
yp = y1 + ((y2-y1)/(x2-x1)) * (xp - x1)
print('Interpolated value at %0.4f is %0.4f' %(xp,yp))
print('The linear polynomial is: ',y1,'+',((y2-y1)/(x2-x1)),'*(x-(',x1,'))')
